Repository 1oT-Itty/itty-vue-frontend, pull requests merged in 2024-04, with the labels that each got.

#21 [Feat] User page / Login Page 설계
  itty-front-test/assets/css/bootstrap/bootstrap.min.css
  itty-front-test/assets/css/bootstrap/bootstrap.min.css.map
  itty-front-test/assets/css/itboard.css
  itty-front-test/assets/css/login.css
  itty-front-test/assets/css/variables.css
  itty-front-test/assets/js/login.js
  itty-front-test/itboard.html
  itty-front-test/login.html
  itty-front/index.html
  itty-front/src/assets/css/login.css
  itty-front/src/assets/js/login.js
  itty-front/src/components/Footer.vue
  itty-front/src/components/Header.vue
  itty-front/src/components/login-content/LoginContent.vue
  itty-front/src/components/main-content/MainContent.css
  itty-front/src/components/main-content/MainContent.vue
  itty-front/src/components/main-content/css/main.css
  itty-front/src/components/mypage-content/MyPageContent.vue
  itty-front/src/components/mypage-content/UserProfile.vue
  itty-front/src/components/mypage-content/mypage.css
  itty-front/src/main.js
  itty-front/src/pages/Login.vue
  itty-front/src/pages/MyPage.vue
  itty-front/src/router/router.js
Labels: enhancement

#22 [Feat] trend board 화면 설계
  itty-front-test/itboard.html
  itty-front/.vite/deps_temp_3e5a6b5f/package.json
  itty-front/src/components/Footer.vue
  itty-front/src/components/Header.vue
  itty-front/src/components/main-content/MainContent.vue
  itty-front/src/pages/board/TrendBoard.vue
  itty-front/src/router/router.js
Labels: enhancement

#23 [Feat] userinfo page
  itty-front/src/components/mypage-content/ModifyUserInfo.vue
  itty-front/src/components/mypage-content/MyPageContent.vue
  itty-front/src/components/mypage-content/UserHistory.vue
  itty-front/src/components/mypage-content/UserInfo.vue
  itty-front/src/components/mypage-content/UserQnA.vue
  itty-front/src/components/mypage-content/UserScrap.vue
  itty-front/src/components/mypage-content/UserSignout.vue
  itty-front/src/components/mypage-content/mypage.css
  itty-front/src/pages/MyPage.vue
  itty-front/src/router/router.js
Labels: enhancement

#24 [Feat] 로그인/회원가입 페이지 구현
  itty-front/src/assets/css/login.css
  itty-front/src/components/login-content/LoginContent.vue
  itty-front/src/pages/MyPage.vue
Labels: enhancement

#26 [Feat] common function
  itty-front/src/components/Footer.vue
  itty-front/src/components/Header.vue
  itty-front/src/components/main-content/MainContent.vue
  itty-front/src/components/main-content/css/main.css
  itty-front/src/main.js
  itty-front/src/pages/board/TrendBoard.vue
Labels: enhancement

#27 [Feat] 자유게시판 추가
  itty-front/src/assets/css/variables.css
  itty-front/src/components/Header.vue
  itty-front/src/components/main-content/css/main.css
  itty-front/src/components/main-content/img/hero-bg.png
  itty-front/src/pages/board/EventBoard.vue
  itty-front/src/pages/board/FreeBoard.vue
  itty-front/src/pages/board/img/event-test.png
  itty-front/src/router/router.js
Labels: enhancement

#28 [Feat] common function
  itty-front/src/assets/css/login.css
  itty-front/src/assets/img/icon-user.png
  itty-front/src/components/Header.vue
  itty-front/src/pages/board/TrendBoard.vue
Labels: bug, enhancement

#29 [Feat] Trend Board 카테고리 수정
  itty-front/src/assets/css/variables.css
  itty-front/src/assets/vendor/bootstrap/css/bootstrap-reboot.css
  itty-front/src/components/Header.vue
  itty-front/src/components/login-content/LoginContent.vue
  itty-front/src/components/main-content/MainContent.vue
  itty-front/src/components/main-content/css/main.css
  itty-front/src/components/main-content/img/about-bg.png
  itty-front/src/pages/board/FreeBoard.vue
  itty-front/src/pages/board/NewArticle.vue
  itty-front/src/pages/board/TrendBoard.vue
  itty-front/src/router/router.js
Labels: enhancement

#30 Feat: "ERROR 및 TEXT 수정"
  itty-front/src/components/main-content/MainContent.vue
  itty-front/src/pages/board/TrendBoard.vue
Labels: enhancement

#32 [Feat] 회원 페이지((회원 정보 수정, 회원 탈퇴) 추가
  itty-front/src/components/mypage-content/ModifyUserInfo.vue
  itty-front/src/components/mypage-content/UserQnA.vue
  itty-front/src/components/mypage-content/UserSignout.vue
  itty-front/src/pages/board/SelectArticle.vue
Labels: enhancement

#33 [Feat] 단일 게시글 조회
  itty-front/src/pages/board/SelectArticle.vue
  itty-front/src/router/router.js
Labels: enhancement

#35 [Feat] API 연동을 위한 Axios 추가
  itty-front/package-lock.json
  itty-front/package.json
  itty-front/src/api/api.js
  itty-front/src/components/main-content/MainContent.vue
  itty-front/src/main.js
Labels: enhancement

#36 [Feat] "userinfo page 수정"
  itty-front/src/api/api.js
  itty-front/src/components/mypage-content/ModifyUserInfo.vue
  itty-front/src/components/mypage-content/UserInfo.vue
  itty-front/src/components/mypage-content/UserProfile.vue
Labels: enhancement

#37 [Feat] 게시글 댓글, 좋아요
  itty-front/src/api/api.js
  itty-front/src/pages/board/ArticleView.vue
  itty-front/src/pages/board/FreeBoard.vue
  itty-front/src/pages/board/NewArticle.vue
  itty-front/src/pages/board/SelectArticle.vue
  itty-front/src/router/router.js
Labels: enhancement

#40 [Feat] Trend Baord 크롤링된 자료 조회
  itty-front/src/api/api.js
  itty-front/src/pages/board/ArticleView.vue
  itty-front/src/pages/board/TrendBoard.vue
Labels: enhancement

#41 [Feat] 내 프로필 및 홈 화면 리팩토링
  itty-front/src/api/api.js
  itty-front/src/components/Header.vue
  itty-front/src/components/main-content/MainContent.vue
  itty-front/src/components/main-content/css/main.css
  itty-front/src/components/mypage-content/ModifyUserInfo.vue
  itty-front/src/components/mypage-content/MyPageContent.vue
  itty-front/src/components/mypage-content/UserHistory.vue
  itty-front/src/components/mypage-content/UserInfo.vue
  itty-front/src/components/mypage-content/UserProfile.vue
  itty-front/src/components/mypage-content/UserSignout.vue
  itty-front/src/pages/MyPage.vue
  itty-front/src/pages/board/ArticleView.vue
  itty-front/src/pages/board/FreeBoard.vue
  itty-front/src/pages/board/NewArticle.vue
  itty-front/src/pages/board/TrendBoard.vue
  itty-front/src/router/router.js
Labels: enhancement

#45 [Fix] "트렌드 게시글 최신순 조회"
  itty-front/src/pages/board/FreeBoard.vue
Labels: bug
